# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r:
    - oldrel
    - release
    - devel

env:
    - NOT_CRAN="false"

after_success:
    - Rscript -e 'covr::codecov()'

notifications:
    email:
        on_success: change
        on_failure: change
    slack:
        rooms:
            - secure: "GHaA4B8wKhQ1mt9Y9wzsSdQKvC3PMN+KRky3I9rB6EVSUL9ZqDFqB+jJ7u4XQfb0I44yu2OwnjWVvyydTe+KMs0RgoWqXsXESJhw9C9HJq7u27nfIXsMvbW4RwdTDf7dMOFgEcpS085qhSV1bolgZVOp/anPVmc9kj3sYJY7OiClPySgDTTdVunjgWoKNMGi7H3yP0pfpBCZk17jO4LWh2AxdCD5tMurbAMgQafSykgSaAFVvcEhrQIHyizPzZ+bcX34wf4kEsUEVM79Cv41tHKcH4mE8wu9XaDCN05Ef4rJSFYb5YUIudeRpwQxD77obxVTaND5CPIJ2A7s9gSJFpzYWZBoQsDpCsOc31CNWAGFDlsyCZ/SAnGqVS4fN4CW1WXH/DkZOt5I5VOvJgGo/EgMzp635fImB5qNTxGazLjfveP6ZKEdMOQgURcRya+RpmS8rrTitn+0l1dXXf3Qj31Cxvw7++MFmrgAYVozpre57xXXBoFb955xT+H/0i8j6zjatK9A3Nb9EQZEHGAxOQfbYR2hpbO/ItVNwDtPLDssLacVeZlg2xcS96rsgbE0VrebmHjBXhJfdM7Ug1N+yYJmbA5Z1u61ArWxRbxnyoM6+6uoX/e/T4fM45yn3QlNzlJF+jvPRlMTT0l6fOFXF9a9TmAK/UP7bOZXDF8OORk="
        on_success: always # default: always
        on_failure: always # default: always
