# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r:
    - oldrel
    - release
    - devel

env:
    - NOT_CRAN="true"

after_success:
    - Rscript -e 'covr::codecov()'

notifications:
    email:
        on_success: change
        on_failure: change
    slack:
        rooms:
            - secure: "QzKRxavoN5/F3Yctx2l0sO6G0ksnh4Lv8+C/C697o/ClxMCNsJivHigTDemQu9vOj58hEavg76PMokNuvZY+Q2wwRQLjMj+GgocRd23yePQIpVB7ugmhucCH+0w0vQtYGdrnMYAUux5vx5X+12sN9IGTRVXlknSCzUOLXpsGgnEsPLPeOXZZnLkBJwOg0NgxAmXpgglNBPawHRDn3gmDz1YmM+uUgBnIOrNocLmCK844f7E3ae6bIjV7KmQu5+YSzeae63WfltKjMv/ibDc5dsEpGL+c5yq2XXlItaVtB2/rnBcHtPszyyvW754Sm7M2ZFdI7MHP7AmdgvsefuN5LZjyql6v8tjl+0b8JAnvH7SPVdvraVoHT2DQF3n5JIYpijzNotTcXbXj+YnpcOMfyt9vpco+m27IxDDmCc/pcBWx+1t7SZ+DaNwwWNzVNyTUZvcHlgor3ypl01RXqo09jnFg8XxjB/THem28D4+JW+vOkKuWxgavstagpntRrXra6qgI7Ygvhc/KVRW0lVNxzs8ZrcUhEEDSccTy9qBF5nodDJ+BmoU9yaPk34j2qvL8zM869Ae076Ytv745rq6U8LGDcnKtoNpAUmMUZYkZVHFP0lZJi4O1pJMi+kGMMFVeGa9M7y1CbE6Q+tcyDTZCSPOPafwaKVe6Nfiv4AS4R48="
